[manager]
prepend_keymap = [
  { on = "1", run = "plugin-relative-motions 1" },
  { on = "2", run = "plugin-relative-motions 2" },
  { on = "3", run = "plugin-relative-motions 3" },
  { on = "4", run = "plugin-relative-motions 4" },
  { on = "5", run = "plugin-relative-motions 5" },
  { on = "6", run = "plugin-relative-motions 6" },
  { on = "7", run = "plugin-relative-motions 7" },
  { on = "8", run = "plugin-relative-motions 8" },
  { on = "9", run = "plugin-relative-motions 9" },
]

keymap = [
  { on = "q", run = "quit" },
  { on = "<Esc>", run = "escape"},

  { on = "y", run = "leave" },
  { on = "e", run = "arrow -1" },
  { on = "n", run = "arrow 1" },

  { on = "<C-u>", run = "arrow -50%" },
  { on = "<C-d>", run = "arrow 50%" },
  { on = ["g", "g"], run = "arrow top" },
  { on = "G", run = "arrow bot" },
]
