[env]
WINIT_X11_SCALE_FACTOR = "1"

[window]
opacity = 0.70
padding = { x = 10, y = 10 }

[font]
size = 12
normal = { family = "saucecodepro nerd font", style = "regular" }

[colors.primary]
background = "#000000"
foreground = "#e6e6e6"
[colors.normal]
black = "#333333"
red = "#494949"
green = "#5f5f5f"
yellow = "#757575"
blue = "#8a8a8a"
magenta = "#a0a0a0"
cyan = "#b6b6b6"
white = "#cccccc"
[colors.bright]
black = "#393939"
red = "#4f4f4f"
green = "#656565"
yellow = "#7b7b7b"
blue = "#919191"
magenta = "#a7a7a7"
cyan = "#bdbdbd"
white = "#d2d2d2"

[keyboard]
bindings = [
  # { key = "", mods = "", mode = "", action = "" | chars = ""},
  # { key = "", mods = "", mode = "", action = "" },
]

