[env]
WINIT_X11_SCALE_FACTOR = "1"

[window]
opacity = 0.70
padding = { x = 10, y = 10 }

[font]
size = 12
normal = { family = "saucecodepro nerd font", style = "regular" }

[colors.primary]
background = "#000000"
foreground = "#e6e6e6"
[colors.normal]
black = "#404040"
red = "#525252"
green = "#646464"
yellow = "#767676"
blue = "#898989"
magenta = "#9b9b9b"
cyan = "#adadad"
white = "#bfbfbf"
[colors.bright]
black = "#454545"
red = "#575757"
green = "#696969"
yellow = "#7b7b7b"
blue = "#8e8e8e"
magenta = "#a0a0a0"
cyan = "#b2b2b2"
white = "#c4c4c4"

[keyboard]
bindings = [
  # { key = "", mods = "", mode = "", action = "" | chars = ""},
  # { key = "", mods = "", mode = "", action = "" },
]

