[env]
WINIT_X11_SCALE_FACTOR = "1"

[window]
opacity = 0.70
padding = { x = 10, y = 10 }

[font]
size = 12
normal = { family = "saucecodepro nerd font", style = "regular" }

[colors.primary]
background = "#000000"
foreground = "#e6e6e6"
[colors.normal]
black = "#4c4c4c"
red = "#5b5b5b"
green = "#696969"
yellow = "#787878"
blue = "#868686"
magenta = "#959595"
cyan = "#a3a3a3"
white = "#b2b2b2"
[colors.bright]
black = "#4c4c4c"
red = "#5b5b5b"
green = "#696969"
yellow = "#787878"
blue = "#868686"
magenta = "#959595"
cyan = "#a3a3a3"
white = "#b2b2b2"

[keyboard]
bindings = [
  # { key = "", mods = "", mode = "", action = "" | chars = ""},
  # { key = "", mods = "", mode = "", action = "" },
]

