[env]
WINIT_X11_SCALE_FACTOR = "1"

[window]
opacity = 0.80
padding = { x = 10, y = 10 }

[font]
size = 10
normal = { family = "saucecodepro nerd font", style = "regular" }

[colors.primary]
background = "#16161e"
foreground = "#8f94b8"
[colors.normal]
black   = "#363b54"
red     = "#f7768e"
green   = "#41a6b5"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#bb9af7"
cyan    = "#7dcfff"
white   = "#787c99"

[keyboard]
bindings = [
  # { key = "", mods = "", mode = "", action = "" | chars = ""},
  # { key = "", mods = "", mode = "", action = "" },
]

